### PR TITLE
Explicitly call processAnnotations

### PR DESCRIPTION
**Pull request by jglick**
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

### CODE REVIEW

**Comment by nfalco79** [comment]
you can rebase

**Comment by jglick** [comment]
Note that when merging you can choose a rebase option, without needing action from the PR author. Or if you want all PRs to be tested against latest `master`, just set up branch restrictions.

**Comment by nfalco79** [comment]
> just set up branch restrictions.
are you speaking about github settings (I have not admin role) or some option in the buildPlugin library (I did find any branch or restriction option in main documentation)?

**Comment by jglick** [comment]
> I have not admin role

Ah, never mind then.

**Pull request merged**
