### PR TITLE
Set Skipped tests as Skipped, not Passed

### PR DESCRIPTION
**Pull request by victimsnino**

### CODE REVIEW

**Comment by nfalco79** [comment]
Any details about this PR? Any jenkins issue related?

**Comment by victimsnino** [comment]
Google tests add new functional via GTEST_SKIP(). But Jenkins reports,
that this test passed

**Comment by nfalco79** [comment]
Please fill a new jenkins feature at https://issues.jenkins-ci.org adding details about from which version introduce the skip feature and an example of test googletest report produced with skipping some test cases.

**Comment by victimsnino** [comment]
https://issues.jenkins-ci.org/browse/INFRA-2285

**Comment by nfalco79** [comment]
The issue has been moved under the from JIRA project.

Please provide a test report file generated that contains skipped test cases to create a test case to provide that your changes works as expected

**Comment by victimsnino** [comment]
[t.zip](https://github.com/jenkinsci/xunit-plugin/files/3676799/t.zip)

**Comment by victimsnino** [comment]
> rebase and add test case

I'm so sorry, but can then you do this fix self? I can't test and run it correctly and do this fix "on the knee"

**Comment by nfalco79** [comment]
The attached report file seems do not contain the explained example.
```
<testcase name="DISABLED_Test3" status="notrun" result="suppressed" time="0" timestamp="1970-01-01T03:00:00" classname="Suite" />
```
is already handled as skipped test case

**Comment by victimsnino** [comment]
It is not true. This report contains a row with **result="skipped"**

**Pull request closed without merging**
